### ISSUE TITLE
customized reference TIL map?

### ISSUE THREAD

**Issue by gt7901b** [carmonalab/ProjecTILs#10]
Hi, 

Is there a way to make customized reference TIL map?

thanks

**Comment by gt7901b** [comment]
I followed this tutorial
https://carmonalab.github.io/ProjecTILs/build_ref_atlas.html to build customized reference. I don't have integrated assay, so I just used which.assay="RNA"

but when I run make.projection, it asked for integrated assay, how to solve this?

thanks

query.projected <- make.projection(seurat.obj, ref = myref, human.ortho=TRUE)


Error in `DefaultAssay<-.Seurat`(`*tmp*`, value = "integrated"): Cannot find assay integrated

Traceback:

1. make.projection(seurat.obj, ref = myref, human.ortho = TRUE)
2. `DefaultAssay<-`(`*tmp*`, value = "integrated")
3. `DefaultAssay<-.Seurat`(`*tmp*`, value = "integrated")
4. stop("Cannot find assay ", value)

**Comment by mass-a** [comment]
You are correct, the algorithm assumes the "integrated" assay is present for the reference atlas. 

If your custom reference does not have this assay, you could simply make a copy of the 'RNA' assay:
```
myref@assays$integrated <- myref@assays$RNA
```
and then follow the [customized atlas](https://carmonalab.github.io/ProjecTILs/build_ref_atlas.html) tutorial as you did.
