### ISSUE TITLE
Error even when redoing the sample code

### ISSUE THREAD

**Issue by ilyiaZhao** [carmonalab/ProjecTILs#13]
I run: 
`> library(ProjecTILs)
> ref <- load.reference.map()
[1] "Loading Default Reference Atlas..."
[1] "/home/ubuntu/TIL/ref_TILAtlas_mouse_v1.rds"
[1] "Loaded Reference map ref_TILAtlas_mouse_v1"
> querydata <- ProjecTILs::query_example_seurat
> query.projected <- make.projection(querydata, ref=ref)
[1] "Using assay RNA for query"
Pre-filtering of T cells (TILPRED classifier)...
Error in value[[3L]](cond) : 
  invalid subscript 'e' in 'altExp(<SingleCellExperiment>, type="character", ...)':
  'RNA' not in 'altExpNames(<SingleCellExperiment>)'
`
But I got the error here. 
`Error in value[[3L]](cond) : 
  invalid subscript 'e' in 'altExp(<SingleCellExperiment>, type="character", ...)':
  'RNA' not in 'altExpNames(<SingleCellExperiment>)'
`
What should I do?

**Comment by ilyiaZhao** [comment]
`> library(ProjecTILs)
Loading required package: Seurat
Attaching SeuratObject
Loading required package: umap
Loading required package: TILPRED
Loading required package: Matrix
> data(query_example_seurat)
> make.projection(query_example_seurat)
[1] "Loading Default Reference Atlas..."
[1] "/home/ubuntu/ref_TILAtlas_mouse_v1.rds"
[1] "Loaded Reference map ref_TILAtlas_mouse_v1"
[1] "Using assay RNA for query"
Pre-filtering of T cells (TILPRED classifier)...
Error in value[[3L]](cond) : 
  invalid subscript 'e' in 'altExp(<SingleCellExperiment>, type="character", ...)':
  'RNA' not in 'altExpNames(<SingleCellExperiment>)'`

**Comment by ilyiaZhao** [comment]
`> data(query_example_seurat)
> query_example_seurat
An object of class Seurat 
14525 features across 1501 samples within 1 assay 
Active assay: RNA (14525 features, 1744 variable features)
> make.projection(query_example_seurat)
[1] "Loading Default Reference Atlas..."
[1] "/home/ubuntu/ref_TILAtlas_mouse_v1.rds"
[1] "Loaded Reference map ref_TILAtlas_mouse_v1"
[1] "Using assay RNA for query"
Pre-filtering of T cells (TILPRED classifier)...
Error in value[[3L]](cond) : 
  invalid subscript 'e' in 'altExp(<SingleCellExperiment>, type="character", ...)':
  'RNA' not in 'altExpNames(<SingleCellExperiment>)'`

**Comment by ilyiaZhao** [comment]
I checked the assay of the seurat object. It did have the RNA assay
`> data(query_example_seurat)
> make.projection(query_example_seurat)
[1] "Loading Default Reference Atlas..."
[1] "/home/ubuntu/ref_TILAtlas_mouse_v1.rds"
[1] "Loaded Reference map ref_TILAtlas_mouse_v1"
[1] "Using assay RNA for query"
Pre-filtering of T cells (TILPRED classifier)...
Error in value[[3L]](cond) : 
  invalid subscript 'e' in 'altExp(<SingleCellExperiment>, type="character", ...)':
  'RNA' not in 'altExpNames(<SingleCellExperiment>)'
> GetAssay(query_example_seurat)
Assay data with 14525 features for 1501 cells
Top 10 variable features:
 Gzmg, Gzmd, Cd74, Lyz2, H2-Ab1, Gzmf, H2-Aa, H2-Eb1, Apoe, Pf4 
> GetAssay(query_example_seurat, assay='RNA')
Assay data with 14525 features for 1501 cells
Top 10 variable features:
 Gzmg, Gzmd, Cd74, Lyz2, H2-Ab1, Gzmf, H2-Aa, H2-Eb1, Apoe, Pf4 `

**Comment by sjcarmona** [comment]
Hello, please see answer in this issue https://github.com/carmonalab/ProjecTILs/issues/11
