### ISSUE TITLE
v1.1.0

### ISSUE THREAD

**Issue by zhangguy** [carmonalab/ProjecTILs#15]
Hi, it seems that there is a dependency "scGate" for the v1.1.0 release: https://github.com/carmonalab/ProjecTILs/releases/tag/v1.1.0 . I couldn't find this package anywhere. Could you advise?

Thanks!

**Comment by mass-a** [comment]
Hello,
please see the installation instuctions in the README file for the development version: https://github.com/carmonalab/ProjecTILs/blob/dev/README.md

**Comment by zhangguy** [comment]
> Hello,
> please see the installation instuctions in the README file for the development version: https://github.com/carmonalab/ProjecTILs/blob/dev/README.md

worked. Thanks!
