### ISSUE TITLE
Subsetting query data

### ISSUE THREAD

**Issue by brhodesford** [carmonalab/ProjecTILs#18]
Hi I'm interested in subsetting my query data, based on the cell types I'm interested in. I've tried doing this using the Seurat subset function:
`merged.subset` <- subset(x = merged.proj, subset = functional.cluster == c('CD8_Tex','CD8_Tpex','CD8_EffectorMemory'))`
However, when I do this I lose a large number of my cells for each group, picture attached.  Is there any to edit this code to make sure I get all the cells for each group of interest? Any help would be greatly appreciated. 

Thanks,
Rhodes
![Screen Shot 2021-09-01 at 2 31 31 PM](https://user-images.githubusercontent.com/78048653/131724782-b2b898f4-60af-4848-a5ff-2599fa3d86b8.png)

**Comment by mass-a** [comment]
Hello Rhodes,
I think you are looking for the `%in%` operator. The following modified query should do the job:
```
merged.subset <- subset(x = merged.proj, subset = functional.cluster %in% c('CD8_Tex','CD8_Tpex','CD8_EffectorMemory'))
```
Best,
-m
