### ISSUE TITLE
Human TILs ATLAS

### ISSUE THREAD

**Issue by AteeqKhaliq** [carmonalab/ProjecTILs#2]
Hi,
Thank for making this wounderful package. I am currently having Human cancer single-cell data and i wanted to analyse my data by using ProjecTILS. My question is can I use Default Reference Atlas(Mouse) to analyse Human cancer Single-cell RNAseq data sets?
It would be great if you can let me know where can I find the human reference TILs to use with this package.
Thanks a lot for your help.
Have a great day,
Ateeq

**Comment by sjcarmona** [comment]
Hi Ateeq, thank you for your comment. Currently we provide a reference for mouse T cells only, for which we are confident about all subtypes. A human equivalent atlas is ongoing work. However, you could try an exploratory analysis projecting human T cells using mouse orthologs over the mouse reference. Let us know if you would like to discuss about it

**Comment by mass-a** [comment]
The development version of ProjecTILs now supports projection of human data onto a mouse reference atlas. Get it with:
```
remotes::install_git("https://gitlab.unil.ch/carmona/ProjecTILs.git", branch = "v0.4.1")
```

And then turn on the `human.ortho` flag when running the projection algorithm, e.g.
```
query.projected <- make.projection(query.object, ref=ref, human.ortho = T)
```

Take a look at this [case study](https://carmonalab.github.io/ProjecTILs_CaseStudies/SadeFeldman_ortho.html) for a worked-out example.

Cheers!
-m
