### ISSUE TITLE
What normalization has been done to data? 

### ISSUE THREAD

**Issue by njbernstein** [carmonalab/ProjecTILs#28]
I downloaded the seurat object from https://spica.unil.ch/refs. 

I'm wondering for the following RNA data
```
b <- readRDS('/group/singlecell/mouse/andreata_2021_t_cell_atlas/ref_TILAtlas_mouse_v1.rds')
b@assays$RNA@data
```
is the counts normalized in the following way: log (1 + 10,000 x / S)? as describe in the paper

**Comment by mass-a** [comment]
Hello,
for the TIL atlas, the count data was normalized using the `NormalizeData` function from Seurat with default parameters – this applies a log-normalization with scaling factor of 10,000 as you indicated.
