### ISSUE TITLE
Error using docker images

### ISSUE THREAD

**Issue by bitcometz** [carmonalab/ProjecTILs#30]
hello,

Thank you very much for creating such great software !!!

I download the images and run following the suggestions:

```shell
docker run --rm -p 8787:8787 -e PASSWORD=pass mandrea1/projectils_demo:1.0.0
remotes::install_github("carmonalab/UCell")
```

But I met some erros:
```
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
ERROR: lazy loading failed for package ‘BiocGenerics’
* removing ‘/home/rstudio/renv/library/R-4.0/x86_64-pc-linux-gnu/BiocGenerics’
* installing *binary* package ‘bitops’ ...
* DONE (bitops)
* installing *source* package ‘GenomeInfoDbData’ ...
** using staged installation
** data
** inst
** help
*** installing help indices
** building package indices
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
```

Best

**Comment by mass-a** [comment]
Hello,
within the container (either interactively in a browser at `localhost:8787` or using command line) all necessary packages are already installed, so you don't have to install anything. You can see some examples on the README file on dockerhub: https://hub.docker.com/repository/docker/mandrea1/projectils_demo

That said, we have not updated the docker image for ProjecTILs in a while, so you will find only v1.1.0 as the latest for the moment being.

Best,
-m

**Comment by bitcometz** [comment]
Thanks ！！！

**Comment by bitcometz** [comment]
Great, it works well and looking forward the new image. Thanks !!!

![image](https://user-images.githubusercontent.com/13601652/155662227-d5212d57-007f-45d5-a3ba-2e3e706a2f2d.png)

Best
