### ISSUE TITLE
Possibility to plot signatures scores in addition to individual genes in plot.states.radar 

### ISSUE THREAD

**Issue by kaizen89** [carmonalab/ProjecTILs#38]
Hi,
I was wandering if you could add the possibility to plot gene signatures alongside individual genes in `plot.states.radar `.
That would be really great.
Thanks!

**Comment by mass-a** [comment]
Thanks for the suggestion!

with the latest version of ProjecTILs you can now generate radar plots for gene signatures. These must be stored in metadata both of the reference and the query. When you run`plot.states.radar`, you can specify the metadata columns that store the signatures using the `meta4radar` parameter. See an example in this [demo section](https://carmonalab.github.io/ProjecTILs.demo/tutorial.html#compare-gene-programs).

Cheers
-m

**Comment by kaizen89** [comment]
Cool, thanks!
