### ISSUE TITLE
Package test failed

### ISSUE THREAD

**Issue by gianfilippo** [carmonalab/ProjecTILs#45]
Hi,

I should also report that the test data failed as well.

I should have mentioned that I am running R 4.2.0

Thanks

Output and error below:
> library(ProjecTILs)
> data(query_example_seurat)
> 
> Run.ProjecTILs(query_example_seurat)
[1] "Loading Default Reference Atlas..."
[1] "/Seurat/ref_TILAtlas_mouse_v1.rds"
[1] "Loaded Reference map ref_TILAtlas_mouse_v1"
[1] "Using assay RNA for query"
Pre-filtering cells with scGate...
No scGate model specified: using default filter for T cells

### Detected a total of 34 non-pure cells for Target (2.27% of total)
[1] "34 out of 1501 ( 2% ) non-pure cells removed. Use filter.cells=FALSE to avoid pre-filtering"
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Aligning query to reference map for batch-correction..."
  |======================================================================| 100%
Computing within dataset neighborhoods
Finding all pairwise anchors
Finding neighborhoods
Finding anchors
	Found 645 anchors
  SD on anchor distances: 0.088

Projecting corrected query onto Reference PCA space

Projecting corrected query onto Reference UMAP space
Error in cellstate.predict(ref = ref, query = x, reduction = reduction,  : 
  trying to get slot "misc" from an object of a basic class ("NULL") with no slots

**Comment by gianfilippo** [comment]
Hi,

I believe this error is caused by the missing ref in the cellstate.predict function call within Run.ProjecTILs. Nothing to do with my other issue

Thanks

**Comment by mass-a** [comment]
Hello Gianfilippo,

indeed one has to explicitly provide the reference to `Run.ProjecTILs`; we updated the Readme to specify this. Thanks for reporting the issue.

-m
