### ISSUE TITLE
Should I filter the res based on functional.cluster.conf?

### ISSUE THREAD

**Issue by DadongZ** [carmonalab/ProjecTILs#5]
I analyzed my human data based on orthologs and I am wondering whether I should filter the results based on functional.cluster.conf.
```
summary(tils_meta$functional.cluster.conf)
Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.20    0.55    0.80    0.75    0.95    1.00
```

Would you suggest a low score means less likely of the predicted functional cluster?

**Comment by mass-a** [comment]
You are correct, low `functional.cluster.conf` scores indicate low confidence in the assigned functional cluster. Cells are assigned to a given cluster by the consensus of the k-neareast neighbors (with `k=20` by default), and the confidence score is simply the fraction of the k neighbors that agree on the cluster assignment.

So yes, if you require confident cluster assignments, you could think of filtering out cells with low scores, e.g. `functional.cluster.conf<0.5`.
