### ISSUE TITLE
potential issue with merge.Seurat.embeddings

### ISSUE THREAD

**Issue by gianfilippo** [carmonalab/ProjecTILs#50]
Hi,

if I use the merge.Seurat.embeddings and then try to subset the resulting object, all cell.embeddings (pca, umap) are lost in the subset.
>query.projected.merged <- Reduce(ProjecTILs:::merge.Seurat.embeddings, query.projected)
> query.projected.merged
An object of class Seurat 
29698 features across 43174 samples within 2 assays 
Active assay: integrated (702 features, 0 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
>subset(query.projected.merged. subset=Group=="Post")
An object of class Seurat 
29698 features across 35069 samples within 2 assays 
Active assay: integrated (702 features, 0 variable features)
 1 other assay present: RNA

If I use the original merge 
query.projected.merged <- merge(query.projected[[1]], query.projected[2:length(query.projected)], merge.dr = c('pca','umap'))
> query.projected.merged
An object of class Seurat 
29698 features across 43174 samples within 2 assays 
Active assay: integrated (702 features, 0 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
>subset(query.projected.merged. subset=Group=="Post")
An object of class Seurat 
29698 features across 35069 samples within 2 assays 
Active assay: integrated (702 features, 0 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap

Also, the UpdateSeuratObject outputs an error message on the merged object generated by ProjecTILs:::merge.Seurat.embeddings
UpdateSeuratObject(query.projected.merged)
Validating object structure
Updating object slots
Ensuring keys are in the proper structure
Error: All cells in the object being added must match the cells in this object

**Comment by mass-a** [comment]
Hello Gianfilippo,

to be honest I could not reproduce the issue.
However, I agree it's best to rely on Seurat's native `merge` function (I didn't know it allowed merging dimreds); so I updated `merge.Seurat.embeddings` to use the `merge.dr` parameter - by default merging all dimreds shared by the two objects. Please test the latest version of ProjecTILs and let me know if the problem persists.

Best
-m

**Comment by gianfilippo** [comment]
Hi,

thanks for looking into it.

Best
