### ISSUE TITLE
Human CD4 and CD8 TILs references

### ISSUE THREAD

**Issue by gianfilippo** [carmonalab/ProjecTILs#52]
HI,

I could not find a description of how you 'transformed' the original data from the Science paper into a ProjecTILs reference.

I am asking since in  Fig 1 (Zhang et al.) the CD8 UMAP has 17 clusters grouped into 8 large categories (Tn, Tem, Temra, Tex, Trm,Tc17, ISG+, KIR+ NK-like). The reference, instead, has 7 categories (Tn, Tem, Temra, Tex, Tcm, Tpex, MAIT) and only the first 4 match.

Could you please clarify ?

Thanks

**Comment by mass-a** [comment]
Hello Gianfilippo,

we did not use the cell type annotations from the Zhang et al. Science paper. Their reference was integrated using harmony and cannot be directly used as a ProjecTILs reference, as it does not return corrected expression counts.

The CD4 T cell reference was indeed built from the collection of datasets assembled by Zhang et al., but re-doing dataset selection and integration from scratch. The CD8 T cell reference was built from the dataset collection found at [utility](https://github.com/ncborcherding/utility), as also briefly described in the Readme of [ProjecTIL's GitHub](https://github.com/carmonalab/ProjecTILs/blob/master/README.md#reference-maps). If you are interested, the code for the integration and annotation of the CD8 T cell reference can be found at the following repository: https://github.com/carmonalab/CD8_human_TIL_atlas_construction

Best
-massimo
