### ISSUE TITLE
Error: object 'ffi_standalone_check_number_1.0.7' not found

### ISSUE THREAD

**Issue by dkwon6** [carmonalab/ProjecTILs#53]
I am trying to execute the Run.ProjecTILs command on a scRNAseq dataset. 

I first ran it on it with cell.filter = TRUE using the CD4 reference atlas with no issues.

I then annotated CD4 cells using another tool, subsetted the scRNAseq to contain only CD4 cells and then ran it with cell.filter = FALSE. Other than two messages stating that direct projection was used for two of my patients, the analysis went without a hitch. However, when I do anything with the output data, I get the following error: 

Error in .standalone_types_check_dot_call(ffi_standalone_check_number_1.0.7,  : 
  object 'ffi_standalone_check_number_1.0.7' not found

I would appreciate any help.

**Comment by mass-a** [comment]
Hello,

it may be an issue with the ggplot and rlang versions. Please have a look at the following thread:
https://github.com/tidyverse/ggplot2/issues/5235

Hope it helps,
-m

**Comment by dkwon6** [comment]
Yeah I looked through that thread prior to posting this issue. Reinstalled the packages and it didn't go away. Ultimately, I left that side of the analysis for a while, and then came back to the pipeline and for some reason it worked at the end. Not a satisfying conclusion to the question but I have my analysis which is all that matters. Thanks!
