### ISSUE TITLE
namespace error in installation

### ISSUE THREAD

**Issue by chjp** [carmonalab/ProjecTILs#6]
Hi,
Thanks for developing the package.
I encountered some errors (shown below) in the installation process. Do you have any suggestions? Thank you.
        Warning: namespace ‘Seurat’ is not available and has been replaced
        by .GlobalEnv when processing object ‘query_example_seurat’
        Warning: namespace ‘Seurat’ is not available and has been replaced
        by .GlobalEnv when processing object ‘query_example_seurat’
        ** byte-compile and prepare package for lazy loading
        Error: package or namespace load failed for ‘Seurat’:
         (converted from warning) replacing previous import ‘spatstat.utils::RelevantNA’ by ‘spatstat.sparse::RelevantNA’ when loading ‘spatstat.geom’
        Error: package ‘Seurat’ could not be loaded
        Execution halted
        ERROR: lazy loading failed for package ‘ProjecTILs’

**Comment by mass-a** [comment]
Hello,

it seems that Seurat cannot be loaded due to some warning being converted to an error.
You could try to change that behavior by setting:
```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```
If the warning was harmless you should be able to proceed with the installation.
