### ISSUE TITLE
How to use Run.Projectils with Harmony.

### ISSUE THREAD

**Issue by mckoch234** [carmonalab/ProjecTILs#63]
I tried using reduction ="harmony" with run.projectils but it's giving me an error saying there are no cell embeddings, even though there are cell embeddings in the reduction.

**Comment by mass-a** [comment]
Hi, the `reduction` parameter refers to the low-dimensional space in which to calculate nearest neighbors between cells of the reference and projected cells of the query, and in this way assign predicted labels. The references do not have a "harmony" embedding (default is 'pca'). We can improve the documentation to avoid confusion.
