### ISSUE TITLE
Error when trying ProjecTILs.classifier on object list

### ISSUE THREAD

**Issue by halterc** [carmonalab/ProjecTILs#64]
Hi,
in contrast to Run.ProjecTILs, which runs just fine taking as input a list of seurat objects, ProjecTILs.classifier returns an error:
Error in ProjecTILs.classifier(test, map, ncores = 3) : 
  Query must be a single Seurat object

EDIT:
Instead of supplying a list of seurat objects directly, supplying a single seurat object to ProjecTILs.classifier and supplying the "split.by" parameter (e.g. split object by sample into list of objects) provides a workaround.

**Comment by mass-a** [comment]
Good suggestion, this has now been implemented in the latest version of ProjecTILs.

You should now be able to run `ProjecTILs.classifier()` either on a single object (optionally splitting by a metadata column) or on a list of objects. In the latter case, parallel processing is also available (`ncores` parameter) for the analysis of multiple samples in parallel.

-m
