### ISSUE TITLE
make.reference function reports error

### ISSUE THREAD

**Issue by LiHangzls** [carmonalab/ProjecTILs#67]
In R version 4.2.3 (2023-03-15), an error occurs when running the code
ref <- make.reference(ref = ref.data, ndim = 10, recalculate.umap = TRUE, annotation.column = "anno")
Error in svd(x, nu = 0, nv = k) : a dimension is zero

**Comment by mass-a** [comment]
Hello, it would be helpful to know what is your input dataset. Would you be able to share it, in order for us to reproduce your error?
