### ISSUE TITLE
Online dataset browser is currently inactive

### ISSUE THREAD

**Issue by edridgedsouza** [carmonalab/ProjecTILs#68]
Unsure whether this is an issue with my network connection or if it's server-side. Currently, any attempt to visit https://spica.unil.ch/ or any of its dataset exploration pages is met with an error message "502 Bad Gateway  nginx/1.25.3". Apologies if this is indeed an issue on my end, though I haven't had issues with other sites despite my connection being unstable

**Comment by mass-a** [comment]
Hello Edridge,
the server appears to be up and running on our end; perhaps it was out temporarily? Can you try again?

**Comment by edridgedsouza** [comment]
Yes, it seems to be working now when I try on a different network. Still not sure what the issue was; I can only assume it may be related to my end of the connection. Perhaps an issue with blocked IP addresses on my uni's VPN?

Thank you
