### ISSUE TITLE
Projection of Proliferating T cells

### ISSUE THREAD

**Issue by rana228** [carmonalab/ProjecTILs#69]
Hi,

Thank you for this package.

I work in Prof. Luca Gattinoni's Group (LIT, Regensburg). 

I have few queries:

1. I was able to project my data on mouse TILAtlas using ProjecTILs Classifier. But our dataset also contains proliferating T cell population and I would like to project and highlight them separately on the projected UMAP, could you please help me out with this.

2. The query map rotates to different position, is there a function or parameter in your package to keep the query map in original position.

3. Also I couldn't use CD8 LCMV Atlas (ref_LCMV_Atlas_mouse_v1.rds), I am getting this error

Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in slot(object = object, name = s): no slot of name "images" for this object of class "Seurat"

I tried all the solution that you have mentioned in other similar queries but nothing worked. 

Thank you for your time.

**Comment by mass-a** [comment]
Hello,
thanks for your interest in the package.

1. In general most T cell subtypes can be or not be proliferating, so we tend to not consider proliferating cells as a separate cell type. I would suggest to evaluate proliferation as a separate axis of variation, for example by signature scoring:
```r
# Here apply a simple signature, but one could use other signatures from literature
signatures <- list(prolif = c("Mki67","Top2a","Stmn1","Birc5"))

library(UCell)
query.projected <- AddModuleScore_UCell(query.projected, features = signatures, assay="RNA")
FeaturePlot(query.projected, features=c("prolif_UCell"))
```

2. I am not sure what you mean by this; can you share some code and more information?

3. This is probably an issue with Seurat versions. Please try running the following command on the reference object:
```r
ref <- UpdateSeuratObject(ref)
```

Best
-m

**Comment by rana228** [comment]
Hi,

Thank you for your quick response.

1. Thank you for the code, with this code I could see many proliferating cells. So I would like to highlight these as separate cell type on the UMAP, is it possible to do so?
As done in this paper: DOI: 10.1126/scitranslmed.adh9562](https://doi.org/10.1126/scitranslmed.adh9562) 
Sample Plots from this paper: T_Proliferating_Cells.png

2. As you can see in the two UMAP's, the position or orientation of the clusters is different as compared to the original UMAP. So I just wanted to know why it is happening and how to fix it. I am using below code:

'''
seurat <- readRDS("SeuratObj.rds")
ref <- readRDS("ref_TILAtlas_mouse_v1.rds")
query.projected <- ProjecTILs.classifier(query = seurat, ref = ref)
plot.projection(query.projected, linesize = 0.5, pointsize = 0.5)

'''
3. This is working now.

4. Also I would like to remove TH1 cells from the UMAP, how can I do this?

Thank you once again for your time.

![Projected_UMAP](https://github.com/carmonalab/ProjecTILs/assets/113985353/8fbdf2b7-a9c2-4602-afba-96e4cf1e9848)
[UMAP_Original.pdf](https://github.com/carmonalab/ProjecTILs/files/13774013/UMAP_Original.pdf)
![T_Proliferating_Cells](https://github.com/carmonalab/ProjecTILs/assets/113985353/8cbef37a-f4a4-4e15-944a-b15ca3e42a12)

**Comment by rana228** [comment]
Hi @mass-a ,

Could you please guide me so that I can complete this task. This is a bit urgent.

Thank you for your time and help.

**Comment by mass-a** [comment]
Hello @rana228

1. If you wish to add an additional cell type (the "proliferating" cells), you can of course do so. You could set a threshold on the UCell score for your proliferating signature, and assign the cells with score above the threshold to the new cell type. If the cell type metadata is a factor, you may have to add the new cell type as an additional factor level.

2. Since you used the `ProjecTILs.classifier()` function, which only transfers labels from the reference to the query, you can just use standard Seurat functions to plot the new labels in the original space, e.g.
```r
seurat <- readRDS("SeuratObj.rds")
ref <- readRDS("ref_TILAtlas_mouse_v1.rds")
seurat <- ProjecTILs.classifier(query = seurat, ref = ref)
DimPlot(seurat, group.by="functional.cluster")
```

4. I can either remove them from the reference before projection, or remove them (or set them to NA) in the query object after the label transfer. The metadata column you would want to modify/use for subsetting is "functional.cluster".

**Comment by rana228** [comment]
Hi @mass-a ,

Thank youso much for your quick response.

Solutions for queries 2 and 4 worked.

**Regarding solution for query 1:** Please correct me if I am wrong, so you suggested to 

a) calculate the score using UCell for Proliferating signatures and then add to Reference Mouse Atlas. As per your UCell manual (https://bioconductor.org/packages/release/bioc/vignettes/UCell/inst/doc/UCell_Seurat.html) I completed this with below code

```
library(UCell)
library(Seurat)
ref <- readRDS("ref_TILAtlas_mouse_v1.rds")

prolif_signatures = list(proliferating.cells = c("Atad2", "Blm",  "Brip1",  "Casp8ap2", "Ccne2",  "Cdc45",  
                                                 "Cdc6",  "Cdca7", "Chaf1b","Clspn", "Dscc1",  "Dtl",  "E2f8",
                                                 "Exo1", "Fen1", "Gins2", "Gmnn",  "Hells", "Mcm2", "Mcm4",
                                                 "Mcm5", "Mcm6", "Msh2", "Nasp", "Pcna", "Pola1", "Pold3",   
                                                 ))

ref.seurat.object <- AddModuleScore_UCell(ref, 
                                      features=prolif_signatures, name=NULL)
head(ref.seurat.object[[]])

```
b) assign these as new celltype based on threshold value and If the cell type metadata is a factor, you may have to add the new cell type as an additional factor level: How do I perform this part? Could you please give me some example code as I don't have much experience with scRNA analysis.

Thank you!!

**Comment by mass-a** [comment]
I don't think you need to modify the reference map. You could simply calculate proliferation signature scores directly on the query dataset, and assign a new cell type based on these scores (overwriting the existing cell type for these cells).

**Comment by rana228** [comment]
Hi @mass-a ,

Thank you for the quick reply.

But if I don't modify the reference map then how will the projection work because as I mentioned initially there are few proliferating cells which are annotated as CD8_Tex after projection (my original clusters are 0-3) and I would like to subset these few cells as Tprolif cells.

**You could simply calculate proliferation signature scores directly on the query dataset, and assign a new cell type based on these scores (overwriting the existing cell type for these cells).** : In UCell manual it is not specified that how I can annotate a cluster based on UCell score cutoff as Seurat doesn't have a function to do signature score based cluster annotation.

Thank you!!

**Comment by mass-a** [comment]
As I previously suggested, you would need to set a threshold on the proliferation score.
Here's some code:
```r
library(UCell)
signatures <- list(prolif = c("Mki67","Top2a","Stmn1","Birc5"))
query.projected <- AddModuleScore_UCell(query.projected, features = signatures, assay="RNA")

#distribution of proliferation scores
hist(query.projected$prolif_UCell)

#add new "proliferating" cell type
thr <- 0.2
query.projected$functional.cluster[query.projected$prolif_UCell > thr] <- "Proliferating"
table(query.projected$functional.cluster)
```

The threshold is somewhat subjective; you may want to inspect the distribution of scores and choose a threshold that will correspond to your definition of proliferating cell.

**Comment by rana228** [comment]
Hi @mass-a ,

Thank you so much for taking out time from your busy schedule to address all my queries so promptly.
