### ISSUE TITLE
Human CD4 and CD8 original vs new annotation

### ISSUE THREAD

**Issue by gianfilippo** [carmonalab/ProjecTILs#70]
Hi,

do you have the metadata related to the original annotation for CD4 and CD8 (or just one of them) ?

Thanks

**Comment by mass-a** [comment]
Hello Gianfilippo,
the CD8T map is built from the collection of datasets from [uTILity](https://github.com/ncborcherding/utility). These come from different studies, and not all provide cell type annotations. You may be able to track down annotations from the original studies by the sample ID in uTILity, which is also stored in the `SampleLabel` metadata in our reference.

As for the CD4T map, it was generated from the collection of datasets by [Zheng et al. Science 2021](https://www.science.org/doi/10.1126/science.abe6474). Here the authors did come up with cell type annotations in their meta-analysis. While we didn't store them, you should be able to link the annotations by matching the cell barcodes.

I hope this is useful,
-m

**Comment by gianfilippo** [comment]
Thanks.

**Comment by mehurwitz1** [comment]
Hi,

We are using projecTILs to assign cell types to our study of melanoma TIL that we isolate from the melanoma and grow up in vitro. We were struck by the fact that we see almost no Th1 or Th2 cells but a large number of Th17. Has anyone noted this before and is there a simple explanation? We would have expected a large number of Th1 in our samples and few Th17.

Thanks a lot,
Mike

**Comment by mass-a** [comment]
Hello Mike,

perhaps you can confirm whether these are actually Th17 or if that is a misclassification by ProjecTILs. Do the predicted Th17 express markers of this subtype, or do they rather have Th1/Th2 transcriptional phenotypes?

**Comment by mehurwitz1** [comment]
Unfortunately, we don't have the cells to look at protein surface markers. We will look back at the transcriptional phenotypes in more detail to see. 

Thanks a lot,
Mike
