### ISSUE TITLE
Unclosed radar plots for plot.states.radar

### ISSUE THREAD

**Issue by DavidJDeGeorge** [carmonalab/ProjecTILs#75]
I am having trouble with the radar plots. For some reason they aren't closing (the first and last points aren't connected) so the shading is all off. In the examples, the radar plots look fine though.

I have attached an example.

![image](https://github.com/carmonalab/ProjecTILs/assets/87787917/d9ebb91d-7f1f-4be8-b311-c0e15a41ebbc)

**Comment by mass-a** [comment]
Hello David,
can you share a reproducible example that shows this behavior? and your SessionInfo?

**Comment by mass-a** [comment]
Indeed I have now also experienced this behavior. I traced it down to a recent ggplot2 update, as also reported here:
https://github.com/tidyverse/ggplot2/issues/5660

We'll work on updating the visualization, thanks for reporting.
