### ISSUE TITLE
Error using the mouse CD8 T cell atlas (outdated Seurat data structure?)

### ISSUE THREAD

**Issue by ycl6** [carmonalab/ProjecTILs#77]
Hi, the "mouse TIL atlas" and "mouse acute and chronic viral infection CD4 T cell atlas" both load and run fine with the `make.projection` function. 

But when I am using the "mouse acute and chronic viral infection CD8 T cell atlas", I had the following message:

```
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in slot(object = object, name = s): no slot of name "images" for this object of class "Seurat"
```

I have to use Seurat's `UpdateSeuratObject` fcuntion to update the object in order for me to use this atlas for projection.

**Comment by mass-a** [comment]
Yes, for references generated before Seurat 5 it may be necessary to run `UpdateSeuratObject()` on the reference object. Thanks for reporting!

**Comment by ycl6** [comment]
Thanks @mass-a. I'll close the issue now.
