### ISSUE TITLE
problem in installation project TILS

### ISSUE THREAD

**Issue by rezath17** [carmonalab/ProjecTILs#78]
Hi 
I tried to install project TILS, but I faced an error message, anyone have idea about the possible reason?
`
> remotes::install_github("carmonalab/ProjecTILs")
Downloading GitHub repo carmonalab/ProjecTILs@HEAD
Skipping 15 packages ahead of CRAN: zlibbioc, XVector, GenomeInfoDbData, S4Arrays, GenomeInfoDb, IRanges, Biobase, MatrixGenerics, DelayedArray, GenomicRanges, BiocGenerics, S4Vectors, SummarizedExperiment, SingleCellExperiment, BiocParallel
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\ralimohammadi\AppData\Local\Temp\Rtmp4cOHPr\remotes4e3c212a1fab\carmonalab-ProjecTILs-4d73208/DESCRIPTION' (769ms)
─  preparing 'ProjecTILs':
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'ProjecTILs_3.3.1.tar.gz'
   
* installing *source* package 'ProjecTILs' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'UCell' 2.4.0 is being loaded, but >= 2.6.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'ProjecTILs'
* removing 'C:/Users/ralimohammadi/AppData/Local/Programs/R/R-4.3.3/library/ProjecTILs'
Warning in i.p(...) :
  installation of package ‘C:/Users/RALIMO~1/AppData/Local/Temp/Rtmp4cOHPr/file4e3c59167a5b/ProjecTILs_3.3.1.tar.gz’ had non-zero exit **status**
`

**Comment by rezath17** [comment]
Solved by installing DESeq2 package!
`
BiocManager::install("DESeq2")

`

**Comment by mass-a** [comment]
Hi, from the error message:
```
namespace 'UCell' 2.4.0 is being loaded, but >= 2.6.0 is required
```
You need to update your version of UCell to 2.6.0 or higher. DESeq2 is not required by ProjecTILs, but perhaps by updating it you also updated UCell?
