### ISSUE TITLE
Error while loading the refernce mouse TIL dataset

### ISSUE THREAD

**Issue by itamuria** [carmonalab/ProjecTILs#79]
After running load reference 

ref <- ProjecTILs::load.reference.map()

I have the next error:

Error in value[[3L]](cond) : 
  Reference object C:/ref_TILAtlas_mouse_v1.rds is invalid

**Comment by mass-a** [comment]
Hello,
almost certainly it's a problem with the download of the reference map. Try removing the file "ref_TILAtlas_mouse_v1.rds", then set `options(timeout = 3000)` and download the reference object again. Alternatively, you can download it manually from [figshare:12478571](https://figshare.com/articles/dataset/ProjecTILs_murine_reference_atlas_of_tumor-infiltrating_T_cells_version_1/12478571).

Best
-m

**Comment by itamuria** [comment]
Hello, 
Yes, it worked. 
Thanks, 
all the best
