### ISSUE TITLE
Alignment failed due to: Error in intI...

### ISSUE THREAD

**Issue by GBeattie** [carmonalab/ProjecTILs#8]
Hey,

I noticed an error when running make.projection, which looks to be circumvented by an alternative approach. We are seeing some fairly major discrepancies between our manually defined clusters and ProjecTILs annotation downstream, so I'm wondering if performance is reduced due to this error, and if so can it be fixed.

If this likely isn't the issue I may open an analysis oriented issue to tackle the discrepancy directly.

Thanks in advance for any assistance, command+error shown below. 

```
> seu.ref <- make.projection(seu, ref=ref, skip.normalize = T)
[1] "Using assay RNA for query"
Pre-filtering of T cells (TILPRED classifier)...
Genes in the gene sets NOT available in the dataset: 
	B.cell: 	10 (20% of 50)
	CAF: 	19 (39% of 49)
	Endo.: 	11 (24% of 46)
	Macrophage: 	3 (7% of 46)
	Mal: 	9 (20% of 45)
[1] "2697 out of 14001 ( 19 % ) non-pure T cells removed.  Use filter.cells=FALSE to avoid pre-filtering (NOT RECOMMENDED)"
[1] "Transforming expression matrix into space of mouse orthologs"
[1] "Aligning query to reference map for batch-correction..."
  |===========================================================================================================================| 100%
Computing within dataset neighborhoods
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  
Alignment failed due to: Error in intI(i, n = d[1], dn[[1]], give.dn = FALSE): invalid character indexing
 

Warning: alignment of query dataset failed - Trying direct projection...
```

**Comment by mass-a** [comment]
Hello Gordon,
quick question: do you see the same error without `skip.normalize=T`? 
this option is to bypass normalization, but in most cases you wouldn't want that.

**Comment by GBeattie** [comment]
Thank you for your response, I've tried that and that has fixed that error, strange though as the object has been run through LogNormalize. The results are marginally better, although some major differences still, we will continue with the analysis and get back in touch if we want to look into the discrepancy further. Thanks again!
