### ISSUE TITLE
Radars don't show expressions

### ISSUE THREAD

**Issue by itamuria** [carmonalab/ProjecTILs#82]
Hello, 

When I plot expressions I can see gene expressions but when I try to do it in radars plot, I don't see them. Why could it be?

`
VlnPlot(querydata, features = genes4radar, stack = T, flip = T, fill.by = "ident",  group.by = "tcell_clustering",# cols = refCols,
        assay = "originalexp") + NoLegend()

plot.states.radar(ref, query = query.projected, genes4radar = genes4radar, min.cells = 5)
`

Please, find attached an example. 

![image](https://github.com/carmonalab/ProjecTILs/assets/40497197/d3df1a8c-3078-4d2a-ac9f-a7887fe1f084)

Thanks, 
All the best,

**Comment by mass-a** [comment]
Hello,
you can try setting the assay for which to plot the radar charts (in your case "originalexp"):
```r
plot.states.radar(ref, query = query.projected, genes4radar = genes4radar, min.cells = 5,
    query.assay="originalexp")
```
Does that work?
-m

**Comment by itamuria** [comment]
Thanks, it worked ;)
