### ISSUE TITLE
Bassez tutorial

### ISSUE THREAD

**Issue by simpakkk** [carmonalab/ProjecTILs#88]
Hi!

I am hoping to attempt to run the Bassez sample dataset/tutorial, but the links provided to download the files here are not working for me: https://github.com/carmonalab/ProjecTILs_CaseStudies/blob/master/CaseStudy_Bassez2021.Rmd

Is it possible to update the links if the file sharing is expired etc? 

Many thanks!

**Comment by mass-a** [comment]
Hello!
thanks for reporting this.

Indeed, we just changed the online data hosting service and some links stopped working. I have now edited the [Bassez et al. case study](https://carmonalab.github.io/ProjecTILs_CaseStudies/Bassez_BC.html) with an updated link to the data. Let us know if this works for you.

Best
-m

**Comment by simpakkk** [comment]
Thank you for addressing this super speedily! I am able to run it now :)
