### ISSUE TITLE
T cell genes not found error

### ISSUE THREAD

**Issue by gt7901b** [carmonalab/ProjecTILs#9]
Hi:

I run ProjectTILs in human T cells data following the tutorial, but got this error. I ran the mouse data with the same command and it works fine. 

What do you think might cause the error?

thanks for your time

query.projected <- make.projection(seurat.obj, ref = ref)

got the error below
[1] "Using assay RNA for query"
Pre-filtering of T cells (TILPRED classifier)...

Error in predictTilState(sce, human = human): T cell genes not found
Traceback:

1. make.projection(seurat.obj, ref = ref)
2. filterCells(query, human = human.ortho)
3. predictTilState(sce, human = human)
4. stop("T cell genes not found")

session info below

R version 4.0.1 (2020-06-06)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.7 (Maipo)

Matrix products: default
BLAS/LAPACK: /data/miniconda3/envs/R_4.0.x/lib/libopenblasp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] gridExtra_2.3               ProjecTILs_0.5.1

**Comment by gt7901b** [comment]
after reading the code, I found that the correct command for human should add human.ortho=TRUE, is that right?

query.projected <- make.projection(seurat.obj, ref = ref, human.ortho=TRUE)

but for large dataset, I got the
Error in asMethod(object): Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

**Comment by mass-a** [comment]
Hello,

I see from your session info that you are running an older version of the method (v0.5.1). I suggest you update to the latest version (v1.0.0), which should automatically detect whether your dataset is murine or human.

Cheers.
