### ISSUE TITLE
error: BiocParallel errors   1 remote errors, element index: 1   0 unevaluated and other errors   first remote error: Error: BiocParallel errors   1 remote errors, element index: 1   0 unevaluated and other errors   first remote error: Error in Layers(query): no "Layers"

### ISSUE THREAD

**Issue by zhangchuy** [carmonalab/ProjecTILs#91]
hello!

when i run code:
 
query.projected <- ProjecTILs.classifier(query = que, ref = ref, ncores = 1)

it occur a error : 

Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in Layers(query): There is no function "Layers"

i don't know how to handle this.

I run in windows, can you help me?
thanks!!

**Comment by mass-a** [comment]
Hello,

it seems it cannot found the "Layers" function, which comes from Seurat version 5.0 or higher. Are you running Seurat 4.*? can you post your `sessionInfo()`?

**Comment by zhangchuy** [comment]
thanks!!!!
I should use Seurat 5.*, but I used Version 4.4.0.
